# Generated by Django 5.0.6 on 2024-07-28 23:54

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_orders_original_bag_orders_stripe_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
